name: jennielim
favicon: null
layout_spectrum: 0.8067978876642883
typography_spectrum: 0.38799
title: Jennie Lim
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e7ed'
    - '#0d0d0f'
    - '#407aab'
    - '#57bcc6'
    - '#968c71'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
